

Collapse AllExpand All Code: All Code: Multiple Code: C# Code: Visual Basic Code: Visual C++   
---  
  
C#Visual BasicVisual C++

Revit 2024 API  
---  
Autodesk.Revit.Exceptions Namespace  
[Send Feedback](javascript:SubmitFeedback\('revitapifeedback@autodesk.com','Revit 2024 API','','','','%0\\dYour%20feedback%20is%20used%20to%20improve%20the%20documentation%20and%20the%20product.%20Your%20e-mail%20address%20will%20not%20be%20used%20for%20any%20other%20purpose%20and%20is%20disposed%20of%20after%20the%20issue%20you%20report%20is%20resolved.%20%20While%20working%20to%20resolve%20the%20issue%20that%20you%20report,%20you%20may%20be%20contacted%20via%20e-mail%20to%20get%20further%20details%20or%20clarification%20on%20the%20feedback%20you%20sent.%20After%20the%20issue%20you%20report%20has%20been%20addressed,%20you%20may%20receive%20an%20e-mail%20to%20let%20you%20know%20that%20your%20feedback%20has%20been%20addressed.%0\\A%0\\d','Customer%20Feedback'\);)  
---  
  
# Classes

|  | Class | Description |
| --- | --- | --- |
|  | [AccessDeniedException](f280ddf5-9f59-eca8-634e-ace30de1f4bb.md) |  |
|  | [ApplicationException](05012a96-16ea-ace7-6115-b45406dacead.md) | The exception that is thrown when a non-fatal application error occurs. |
|  | [ArgumentException](2e6e4206-97a8-dd4b-df5d-4269f4bb6088.md) | The exception that is thrown when one of the arguments provided to a method is not valid. |
|  | [ArgumentNullException](631e1424-60f4-929b-4e52-dda9dcd26316.md) | The exception that is thrown when nullNothingnullptra null reference (Nothing in Visual Basic) is passed to a method that does not accept it as a valid argument. |
|  | [ArgumentOutOfRangeException](60f148c9-ece0-a6bb-4e12-bb4a9c8c8a24.md) | The exception that is thrown when the value of an argument is outside the allowable range of values as defined by the invoked method. |
|  | [ArgumentsInconsistentException](05972c68-fa6d-3a83-d720-ad84fbc4780f.md) | The exception that is thrown when each individual argument is OK, but a joint constraint is violated. |
|  | [AutoJoinFailedException](666f8a45-18c9-0a1f-1a3f-eaa0ac96f23f.md) | The exception that is thrown when an autojoin operation failed. |
|  | [BackgroundTaskCancelledException](656ff28c-486a-49ea-69e7-53ce76f75567.md) | The exception thrown when Revit cancels a background operation. Third-party developers are not expected to catch and handle this exception. Instead, if allowed to propagate back to Revit code, it will be handled by Revit. |
|  | [CannotOpenBothCentralAndLocalException](13aac793-10be-9bed-90d8-5474a05f0fea.md) | The exception thrown when both a central model and also a local file for the same central model are opened in the same session. |
|  | [CentralFileCommunicationException](20094e4f-8326-8378-e5bc-452341d131c2.md) | The exception thrown when there is a network communication error involving a file-based central model. |
|  | [CentralModelAccessDeniedException](3e38b7b1-1ee8-c7f0-6cdd-bacf67bf61f4.md) | The exceptions thrown when a central model can be reached but access is denied due to a lack of access privileges. |
|  | [CentralModelAlreadyExistsException](2ffb2cbc-6ab4-c486-b683-96483f33df78.md) | Exception is thrown when the central model already exists at the specified location. |
|  | [CentralModelContentionException](ad511076-c435-23c1-5720-1205c4ed28b9.md) | The exception thrown when a central model is busy (locked) and the operation is canceled. |
|  | [CentralModelException](0e2ac15f-ca64-42c3-b3ef-e6f7ca1cb59a.md) | The base class for exceptions that are common to both file-based and server-based central models or specific to just file-based central models. |
|  | [CentralModelVersionArchivedException](9b54c5a2-22f3-ac30-3efd-7ef80adff6ea.md) | Exception is thrown when last central version merged into the local model has been archived in the central model. Reload Latest or Synchronized with Central needs to be conducted before the current failed operation is retried. |
|  | [CheckoutElementsRequestTooLargeException](61162ab4-01c4-cf01-d307-fc45c19ad63d.md) | Exception is thrown when too many elements are requested for checkout |
|  | [CorruptModelException](b1a877a7-6c68-c0e4-25c9-005ee153bc60.md) | The exception that is thrown when the model is or seems corrupt. |
|  | [DefaultValueException](b26719be-e9a8-eab2-3fac-66bc8765febe.md) | The exception thrown when Revit cannot initialize a default value for a family parameter. |
|  | [DirectoryNotEmptyException](9614b41a-e3ea-eed0-d74d-57337e6f4888.md) | The exception that is thrown when a method received a directory as an argument and requires that the directory be empty but the directory is not empty. |
|  | [DirectoryNotFoundException](e6614e11-0fd4-df20-0d2d-02722b779128.md) | The exception that is thrown when the specified directory could not be found. |
|  | [DisabledDisciplineException](3693dcdf-67fb-0128-3be8-cad150e9498e.md) | The exception that is thrown when the function cannot execute because a discipline is disabled. The exception specifies which discipline(s) would let the operation succeed. |
|  | [ExternalApplicationException](06e9a9a5-c212-2708-3151-301c1f33a96a.md) | The exception that is thrown when an issue in the Add-Ins resulted in an unexpected error. |
|  | [FamilyContextException](b9aae3f6-b261-5328-d685-63d4ad046506.md) | The exception that is thrown when an operation is invalid in the current family document, because of the type of family. |
|  | [FileAccessException](187d56d7-0b37-699f-2abd-6ddebfa93f1e.md) | The exception that is thrown when the specified file could not be accessed, e.g. read-only, locked by the OS etc. |
|  | [FileArgumentAlreadyExistsException](bffdd5da-7a0a-2450-efa8-84a1deeebae3.md) | The exception that is thrown when the specified file exists. |
|  | [FileArgumentNotFoundException](ca9ccaa9-ed08-d40d-31a7-1af3ad2dcb84.md) | The exception that is thrown when a method received a filename as an argument and requires it to exist as a precondition. |
|  | [FileNotFoundException](73250198-dbc6-e760-4297-ec062f00f574.md) | The exception that is thrown when the specified file could not be found. |
|  | [ForbiddenForDynamicUpdateException](c5b911f6-1e8f-2cd4-6965-286f41221fe0.md) | The exception that is thrown when making or attempting to make changes that are forbidden during dynamic updates to the model. |
|  | [FunctionId](f510babd-969e-98fd-530e-c58fe4c9e5ca.md) | The information of a function throwing an exception. |
|  | [InapplicableDataException](dc1a6d15-8923-a1fe-722a-4e976634a519.md) | The exception that is thrown when attempting to access a piece of data that is structurally not part of an object at the moment. |
|  | [InsufficientResourcesException](658e57bc-6929-4883-d245-dcd832fed696.md) | The exception that is thrown when the OS runs out of resources, e.g. memory, disk space, or USER or GDI objects. |
|  | [InternalException](c52bc6d3-6cd9-26f5-4b27-1646c0711a34.md) | The exception that is thrown when an issue in the Revit code resulted in an unexpected error. |
|  | [InvalidDataStreamException](5501eca1-70f1-3204-fda2-d6abc4e33e03.md) | The exception that is thrown when the reading or saving operation failed due to parsing error. |
|  | [InvalidObjectException](8092dec2-113a-0823-1a09-a46c11f99fea.md) | The exception that is thrown when referencing an object that is no longer valid. |
|  | [InvalidOperationException](9e715f03-3884-e539-4dd6-8d7545733adc.md) | The exception that is thrown when a method call is invalid for the object's current state. |
|  | [InvalidPathArgumentException](3f3c93a6-008b-f9de-40d4-5cd99bb32b34.md) | The exception that is thrown when a method received a pathname as an argument, but the pathname is illegal: too long, invalid characters, etc. |
|  | [IOException](30d0cc9b-741e-7695-4f52-d9d747791ec3.md) | The exception that is thrown when an I/O error occurs. |
|  | [ModificationForbiddenException](53205486-5917-7c33-8e67-e362106ddc97.md) | The exception that is thrown by the undo transaction framework when a modification operation is not allowed. |
|  | [ModificationOutsideTransactionException](8f025460-c283-ea99-aa8a-5a36e11528f4.md) | The exception that is thrown by the undo transaction framework when the modification operation to the model is outside of a transaction. |
|  | [NetworkCommunicationException](77e5da6e-c129-8e56-c944-26d2c5e925a3.md) |  |
|  | [NotTransmittedModelException](6b7f7376-d5bf-e5bd-2c77-446f7c72a047.md) | The exception thrown when OpenOptions were provided to deal with a transmitted model, but the model is not transmitted. |
|  | [ObjectAccessException](7d69a00b-f531-c575-0e55-ea2f3858560d.md) | The exception that is thrown when an operation is denied, e.g. an attempt was made to set a read-only property. |
|  | [OperationCanceledException](aea34480-ceb5-b49f-129d-0799e7bb1c21.md) | The exception that is thrown when an operation is unexpectedly cancelled. |
|  | [OptionalFunctionalityNotAvailableException](0612a676-b6ba-8c37-2e28-b197438305ab.md) | The exception that is thrown when the optional functionality is not available in the installed Revit |
|  | [OutdatedDirectlyOpenedCentralException](d38fd86b-6281-788d-bf20-6b896da2fbbb.md) | The exception thrown when a central model is opened directly and its copy in the session is outdated. If the operation is supported for local files, first resave as local, and try again. |
|  | [RegenerationFailedException](787bb389-74c2-5ce7-cdd6-32211209ded2.md) | The exception that is thrown when a regeneration operation failed. |
|  | [ResourceNotFoundException](4ef7bcee-5831-e2c9-ee4a-06a0dd6c255f.md) |  |
|  | [RevitServerCollaborationNotAvailableException](220ad785-883e-1b26-8eb0-99ffb55605fb.md) | The exception that is thrown when Collaboration fails because of an external resource (e.g., Amazon S3) failure. |
|  | [RevitServerCommunicationException](a0003d89-0113-6623-65da-0db5c568bfb6.md) | The exception that is thrown when there is any network communication error happening. |
|  | [RevitServerException](cb9f496c-f65b-7d27-0fe4-e42f80261b38.md) | The exception that is base class for all exceptions originating from the Revit server. |
|  | [RevitServerInternalException](6dcd093c-d643-07cd-535f-36ffa9d2db52.md) | The exception that is thrown when there is any server internal error happening. |
|  | [RevitServerModelAlreadyExistsException](a3ed0157-0a46-0b62-62db-08112e1645bd.md) | The exception that is thrown when there is a model with the same name already exist. |
|  | [RevitServerModelNameBreaksConventionException](ec0e702a-f076-1b44-4277-feefd39045d4.md) | The exception that is thrown when the model is breaking the project naming convention. |
|  | [RevitServerUnauthenticatedUserException](b9b68e56-c767-4680-a65b-73d268ee8860.md) | The exception that is thrown when an unauthenticated user attempts to initiate a call to RevitServer. |
|  | [RevitServerUnauthorizedException](9e8c1efc-8719-fe01-f311-cfade7b177ed.md) | The exception that is thrown when a call to the server is unauthorized. |
|  | [SchemaException](9f929b36-8215-444e-30fd-518c94fb6d29.md) | The exception thrown when Revit cannot interpret a data structure described by a schema. |
|  | [ServerInternalException](dea21550-dd2d-e9d1-4f2f-5f18e0e58bc4.md) |  |
|  | [TransientElementCreationException](5d572105-6feb-10ad-db16-4d09de36de2e.md) | The exception that is thrown when TransientElementCreationScope is used incorrectly. |
|  | [TransmittedModelException](5fb430a2-bbcc-34d2-6524-f38972b585ac.md) | The exception thrown when model was transmitted (sent by eTransmit) and insufficient OpenOptions were provided to handle its transmitted flag. |
|  | [UnauthenticatedException](e94e82b6-4345-48ca-7be9-fd8393b0ff7f.md) |  |
|  | [WrongUserException](e445bf18-84d1-83f2-6b24-45a6a6fe2bd9.md) | The exception thrown when a local model is manipulated under a different username than it was created with. |
  
Send comments on this topic to [Autodesk](mailto:revitapifeedback%40autodesk.com?Subject=Revit 2024 API)